### ISSUE TITLE
Button appears in PR creation dialog but doesn't do anything

### ISSUE THREAD

**Issue by Coteh** [Jarred-Sumner/1-click-from-github-to-editor#3]
See attached screenshot of PR #2 being created:

![image](https://user-images.githubusercontent.com/3276350/107891589-a802ea80-6eed-11eb-8b7d-7d3cd8ad20e1.png)

After clicking the button, nothing comes up in VS Code. I guess I'm expecting that my Readme change in #2 would come up in this case.

**Comment by Jarred-Sumner** [comment]
Oh wow, I didn't know that button appears there...:joy: 

Thanks for reporting.

Looks like the code for filtering when to place the button is incorrect. On PRs, its supposed to only place it in the files tab. But, there should probably be one there anyway because why not. I'll add it in next release (currently trying to get Windows to work, and I'm very close -- https://github.com/Jarred-Sumner/register-url-windows)

**Comment by Jarred-Sumner** [comment]
![image](https://user-images.githubusercontent.com/709451/107953279-c8639100-6f4f-11eb-85da-47822cf6335c.png)
same thing in release page

**Comment by Jarred-Sumner** [comment]
Fixed
